### ISSUE TITLE
装了之后，收藏了多年的表情全不见了

### ISSUE THREAD

**Issue by yaoxinghui714** [Sunnyyoung/QQTweak-macOS#1]
🐑神有没有解决办法？

**Comment by sunnyyoung** [comment]
@yaoxinghui714 Copy `~/Library/Containers/com.tencent.qq/Data/Documents/` to `~/Documents/`

**Comment by yaoxinghui714** [comment]
@Sunnyyoung 感恩的心

**Comment by sunnyyoung** [comment]
@yaoxinghui714 Fixed 9f3209bc8dc4ab506fb63972598904b379f7c82b
