### ISSUE TITLE
请务必修一下文档被弄乱的问题

### ISSUE THREAD

**Issue by OiCkilL** [Sunnyyoung/QQTweak-macOS#2]
现在QQ版的比微信版的落后太多了

**Comment by sunnyyoung** [comment]
@OiCkilL 因为很少用QQ哈哈，这两天我看看吧

**Comment by luuray** [comment]
MacQQ 6.1 目录还是有点问题，临时这么解决了一下：

> ln -s ~/Library/Containers/com.tencent.qq/Data/Library/Application\ Support/QQ ~Library/Application\ Support/QQ

然后聊天记录和表情就没问题了
